springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

app.bootstrap.user.enabled=true
app.bootstrap.user.name=${BOOTSTRAP_USER_NAME:Admin}
app.bootstrap.user.email=${BOOTSTRAP_USER_EMAIL:admin@gmail.com}
app.bootstrap.user.password=${BOOTSTRAP_USER_PASSWORD:Admin@123}
app.bootstrap.user.role=${BOOTSTRAP_USER_ROLE:ADMIN}
