aws.s3.bucket=${AWS_S3_BUCKET}
aws.s3.region=${AWS_S3_REGION}

sentry.environment=${SENTRY_ENVIRONMENT:production}
sentry.debug=${SENTRY_DEBUG:false}
sentry.traces-sample-rate=${SENTRY_TRACES_SAMPLE_RATE:0.2}
sentry.profile-session-sample-rate=${SENTRY_PROFILE_SESSION_SAMPLE_RATE:0.2}