$kind: http-request
name: Create Account Config
method: POST
url: '{{baseUrl}}/api/admin/config'
order: 1000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "clientId": 1,
      "igUserId": "123456789",
      "accessToken": "your-access-token"
    }
