CREATE TABLE tb_content_idea_runs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id     BIGINT,
    niche         VARCHAR(255),
    provider      VARCHAR(255),
    status        VARCHAR(255),
    started_at    TIMESTAMP WITHOUT TIME ZONE,
    finished_at   TIMESTAMP WITHOUT TIME ZONE,
    ideas_count   INTEGER,
    error_message VARCHAR(1024),
    CONSTRAINT pk_tb_content_idea_runs PRIMARY KEY (id)
);

CREATE TABLE tb_content_ideas
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id         BIGINT,
    title             VARCHAR(255),
    theme             VARCHAR(255),
    objective         VARCHAR(255),
    format            VARCHAR(255),
    hook              VARCHAR(255),
    reason            VARCHAR(255),
    source_terms      VARCHAR(255),
    signal_summary    VARCHAR(255),
    status            VARCHAR(255),
    priority          VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    expires_at        TIMESTAMP WITHOUT TIME ZONE,
    converted_post_id BIGINT,
    CONSTRAINT pk_tb_content_ideas PRIMARY KEY (id)
);

CREATE INDEX idx_content_idea_generated_at ON tb_content_ideas (created_at);

CREATE INDEX idx_content_idea_runs_status ON tb_content_idea_runs (status);

CREATE INDEX idx_content_idea_status ON tb_content_ideas (status);

ALTER TABLE tb_content_ideas
    ADD CONSTRAINT FK_TB_CONTENT_IDEAS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES tb_client (id);

CREATE INDEX idx_content_idea_client_id ON tb_content_ideas (client_id);

ALTER TABLE tb_content_ideas
    ADD CONSTRAINT FK_TB_CONTENT_IDEAS_ON_CONVERTED_POST FOREIGN KEY (converted_post_id) REFERENCES tb_posts (id);

ALTER TABLE tb_content_idea_runs
    ADD CONSTRAINT FK_TB_CONTENT_IDEA_RUNS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES tb_client (id);

CREATE INDEX idx_content_idea_runs_client_id ON tb_content_idea_runs (client_id);

ALTER TABLE tb_client
    ALTER COLUMN drive_link DROP NOT NULL;

ALTER TABLE tb_client
    ALTER COLUMN voice_tone TYPE VARCHAR(1024) USING (voice_tone::VARCHAR(1024));

ALTER TABLE tb_client
    ALTER COLUMN voice_tone SET NOT NULL;