CREATE TABLE tb_comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    text       VARCHAR(2000)                           NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_comments PRIMARY KEY (id)
);

ALTER TABLE tb_comments
    ADD CONSTRAINT FK_TB_COMMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES tb_posts (id);

ALTER TABLE tb_comments
    ADD CONSTRAINT FK_TB_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES tb_users (id);
