-- Migração inicial única (banco do zero)
-- Schema completo já com todos os campos e constraints atuais.

CREATE TABLE tb_users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT ck_tb_users_role_enum CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE tb_client (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    number VARCHAR(50) NOT NULL UNIQUE,
    drive_link VARCHAR(500) NOT NULL,
    niche VARCHAR(255) NOT NULL,
    voice_tone VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    whatsapp_group_id VARCHAR(100),
    whatsapp_group_name VARCHAR(255),
    CONSTRAINT ck_tb_client_status_enum CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE UNIQUE INDEX ux_tb_client_whatsapp_group_id
    ON tb_client (whatsapp_group_id)
    WHERE whatsapp_group_id IS NOT NULL;

CREATE TABLE tb_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    theme VARCHAR(255) NOT NULL,
    objective VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'DEMAND',
    scheduled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    client_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_tb_posts_on_client FOREIGN KEY (client_id) REFERENCES tb_client (id),
    CONSTRAINT fk_tb_posts_on_user FOREIGN KEY (user_id) REFERENCES tb_users (id),
    CONSTRAINT ck_tb_posts_status_enum CHECK (
        status IN ('DEMAND', 'IN_PRODUCTION', 'FINISHED', 'WAITING_APPROVAL', 'SCHEDULE', 'PUBLISHED')
    )
);

CREATE TABLE tb_finance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    description VARCHAR(255),
    value DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    expiration_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    payment_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_tb_finance_on_client FOREIGN KEY (client_id) REFERENCES tb_client (id),
    CONSTRAINT fk_tb_finance_on_user FOREIGN KEY (user_id) REFERENCES tb_users (id),
    CONSTRAINT ck_tb_finance_status_enum CHECK (status IN ('PENDING', 'PAY'))
);

CREATE TABLE tb_post_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    art_s3_key VARCHAR(500) NOT NULL,
    art_name VARCHAR(255) NOT NULL,
    caption TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_at TIMESTAMP WITHOUT TIME ZONE,
    approved_user VARCHAR(255) NOT NULL DEFAULT '',
    whatsapp_stanza_id TEXT UNIQUE,
    whatsapp_sent_at TEXT,
    whatsapp_response_text TEXT,
    CONSTRAINT uq_tb_post_approvals_post UNIQUE (post_id),
    CONSTRAINT fk_tb_post_approvals_post FOREIGN KEY (post_id) REFERENCES tb_posts (id),
    CONSTRAINT ck_tb_post_approvals_status_enum CHECK (status IN ('APPROVE', 'REJECT', 'PENDING'))
);

CREATE TABLE tb_account_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE,
    ig_user_id VARCHAR(64) NOT NULL,
    access_token VARCHAR(2048),
    configured_by VARCHAR(255) NOT NULL,
    configured_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_tb_account_config_client FOREIGN KEY (client_id) REFERENCES tb_client (id)
);

CREATE TABLE tb_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    replaced_by_token_hash VARCHAR(64),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_tb_refresh_tokens_on_user FOREIGN KEY (user_id) REFERENCES tb_users (id)
);

CREATE UNIQUE INDEX ux_tb_refresh_tokens_token_hash
    ON tb_refresh_tokens (token_hash);
