ALTER TABLE tb_task DROP CONSTRAINT FK_TB_TASK_ON_CLIENT;

ALTER TABLE tb_task
    ADD CONSTRAINT FK_TB_TASK_ON_CLIENT
    FOREIGN KEY (client_id)
    REFERENCES tb_client(id)
    ON DELETE SET NULL;
